# List alerts
GET {{sysdig_endpoint}}/api/v2/alerts
Authorization: Bearer {{sysdig_api_key}}

###

# Get alert
GET {{sysdig_endpoint}}/api/alerts/415135
Authorization: Bearer {{sysdig_api_key}}

###

# Delete alert
DELETE {{sysdig_endpoint}}/api/v2/alerts/415183
Authorization: Bearer {{sysdig_api_key}}


###

# List notifications
GET {{sysdig_endpoint}}/api/notificationChannels
Authorization: Bearer {{sysdig_api_key}}


###

# Get notification
GET {{sysdig_endpoint}}/api/notificationChannels/39152
Authorization: Bearer {{sysdig_api_key}}

###

# Delete notification
DELETE {{sysdig_endpoint}}/api/notificationChannels/39160
Authorization: Bearer {{sysdig_api_key}}

###

# Create alert
POST {{sysdig_endpoint}}/api/v2/alerts/create
Authorization: Bearer {{sysdig_api_key}}
Content-Type: application/json

{
    "alert": {
        "name": "Test Alert",
        "description": "Test Alert Description",
        "enabled": true,
        "durationSec": 900,
        "type": "PROMETHEUS",
        "severity": "high",
        "group": "default",
        "config": {
            "query": "(kube_workload_status_desired{kube_cluster_name=~\".*\",kube_namespace_name=~\"calico-system|istio-system.*|kube-system\",kube_workload_name=~\".*\"}\n- kube_workload_status_running{kube_cluster_name=~\".*\",kube_namespace_name=~\"calico-system|istio-system.*|kube-system\",kube_workload_name=~\".*\"})\n> 0\n"
        },
        "notificationChannelConfigList": []
    }
}

###

# Create bulk alerts
POST {{sysdig_endpoint}}/api/v2/alerts/
Authorization: Bearer {{sysdig_api_key}}
Content-Type: application/json

{
    "alerts": [
        {
            "name": "Test Alert 1",
            "description": "Test Alert Description",
            "enabled": true,
            "type": "PROMETHEUS",
            "timespan": 900000000,
            "condition": "(kube_workload_status_desired{kube_cluster_name=~\".*\",kube_namespace_name=~\"calico-system|istio-system.*|kube-system\",kube_workload_name=~\".*\"}\n- kube_workload_status_running{kube_cluster_name=~\".*\",kube_namespace_name=~\"calico-system|istio-system.*|kube-system\",kube_workload_name=~\".*\"})\n> 0\n",
            "severityLabel": "HIGH",
            "valid": true,
            "notificationChannelIds": []
        },
        {
            "name": "Test Alert 2",
            "description": "Test Alert Description",
            "enabled": true,
            "type": "MANUAL",
            "timespan": 900000000,
            "condition": "avg(avg(sysdig_fs_used_percent)) > 90.0",
            "severityLabel": "HIGH",
            "segmentBy": [
                "agent.tag.cluster",
                "host.hostName",
                "fs.mountDir"
            ],
            "segmentCondition": {
                "type": "ANY"
            },
            "filter": "fs.mountDir in (\"/var/data\")",
            "valid": true,
            "notificationChannelIds": []
        }
    ]
}

###

# Create channel
POST {{sysdig_endpoint}}/api/notificationChannels
Authorization: Bearer {{sysdig_api_key}}
Content-Type: application/json

{
    "notificationChannel": {
        "name": "test-channel-2",
        "type": "EMAIL",
        "sendTestNotification": false,
        "enabled": false,
        "options": {
            "notifyOnResolve": true,
            "notifyOnOk": true,
            "emailRecipients": [
                "user@example.com"
            ]
        }
    }

}

###

# List all teams
GET {{sysdig_endpoint}}/api/teams
Authorization: Bearer {{sysdig_api_key}}


###

# Get a team
GET {{sysdig_endpoint}}/api/teams/50429
Authorization: Bearer {{sysdig_api_key}}

###

# Delete a team
DELETE {{sysdig_endpoint}}/api/teams/50426
Authorization: Bearer {{sysdig_api_key}}

###

# Create a team
POST {{sysdig_endpoint}}/api/teams
Authorization: Bearer {{sysdig_api_key}}
Content-Type: application/json


{
    "name": "test2",
    "description": "Test team description",
    "show": "host",
    "theme": "#7BB0B2",
    "canUseSysdigCapture": true,
    "canUseAgentCli": true,
    "canUseCustomEvents": true,
    "canUseAwsMetrics": false,
    "canUseBeaconMetrics": false,
    "canUseRapidResponse": false,
    "users": []
}
